default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'sror_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] || 'root'  %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %>
  socket: /tmp/mysql.sock

  # adapter: mysql2
  # encoding: utf8mb4
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password:
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: sror_development
test:
  <<: *default
  database: sror_test
production:
  <<: *default
  database: sror_production
  username: sror
  password: <%= ENV['SROR_DATABASE_PASSWORD'] %>
# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV["DB_POOL"] || 5  %>
#   database: <%= ENV['DB_NAME'] || 'esports_local_dev' %>
#   username: <%= ENV['DB_USER'] || 'root' %>
#   password: <%= ENV['DB_PASS'] %>
#   host: <%= ENV["DB_HOST"] %>
#   url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
#   reconnect: true
# development:
#   <<: *default
#   database: <%= ENV['DB_NAME'] || 'esports_development' %>

# dev:
#   <<: *default
#   database: <%= ENV['DB_NAME'] || 'esports_dev' %>

# stg:
#   <<: *default
#   database: <%= ENV['DB_NAME'] || 'esports_stg' %>

# tst:
#   <<: *default
#   database: <%= ENV['DB_NAME'] || 'esports_tst' %>

# prd:
#   <<: *default
#   database: esports_prd
#   url: <%= ENV['DATABASE_URL'] %>
